const employees = [
  {
    id: 1,
    firstname: "Amit",
    email: "em1@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Prepare sales report",
        description: "Compile and analyze the weekly sales data.",
        date: "2025-09-05",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Team meeting",
        description: "Attend the Monday sync-up with the product team.",
        date: "2025-09-06",
        category: "Meeting",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Update CRM",
        description: "Add new client details into the CRM system.",
        date: "2025-09-07",
        category: "Data Entry",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    firstname: "Priya",
    email: "em2@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Fix login bug",
        description: "Resolve authentication issue for employee portal.",
        date: "2025-09-05",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Write documentation",
        description: "Document API endpoints for project X.",
        date: "2025-09-10",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Code review",
        description: "Review PRs submitted by junior developers.",
        date: "2025-09-08",
        category: "Review",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Security update",
        description: "Apply latest security patches to server.",
        date: "2025-09-09",
        category: "Maintenance",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstname: "Rohit",
    email: "em3@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        title: "Prepare presentation",
        description: "Design slides for the upcoming client pitch.",
        date: "2025-09-07",
        category: "Presentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Data backup",
        description: "Run and verify weekly data backup.",
        date: "2025-09-05",
        category: "IT",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Market research",
        description: "Collect competitor pricing information.",
        date: "2025-09-12",
        category: "Research",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "System monitoring",
        description: "Check server logs and ensure uptime.",
        date: "2025-09-08",
        category: "IT",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Update knowledge base",
        description: "Add new FAQs to the internal wiki.",
        date: "2025-09-06",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 4,
    firstname: "Neha",
    email: "em4@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Client call",
        description: "Discuss project requirements with client.",
        date: "2025-09-06",
        category: "Meeting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Test new feature",
        description: "Perform QA on recently deployed feature.",
        date: "2025-09-07",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Training session",
        description: "Attend leadership training workshop.",
        date: "2025-09-09",
        category: "Training",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstname: "Sanjay",
    email: "em5@example.com",
    password: "123",
    taskCount: {
      active: 3,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Inventory check",
        description: "Audit office supplies stock.",
        date: "2025-09-05",
        category: "Operations",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Onboard intern",
        description: "Assist in onboarding new marketing intern.",
        date: "2025-09-06",
        category: "HR",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Prepare invoices",
        description: "Generate invoices for August clients.",
        date: "2025-09-07",
        category: "Finance",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Social media post",
        description: "Create LinkedIn post for new product launch.",
        date: "2025-09-08",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Vendor meeting",
        description: "Negotiate new contract with IT supplier.",
        date: "2025-09-10",
        category: "Operations",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
];


const admin = {
  id: 1,
  email: "admin@example.com",
  password: "123",
};


export const setLocalStorage=()=>{
    localStorage.setItem('employees', JSON.stringify(employees))
    localStorage.setItem('admin', JSON.stringify(admin))
}
export const getLocalStorage=()=>{
    const employees= JSON.parse(localStorage.getItem('employees')) 
    const admin= JSON.parse(localStorage.getItem('admin')) 
 return{employees, admin}   
} 